import = [
    "~/.config/alacritty/themes/themes/Cobalt2.toml"
]

[font]
size = 13.0

[font.bold]
family = "FiraCode Nerd Font"

[font.bold_italic]
family = "FiraCode Nerd Font"

[font.italic]
family = "FiraCode Nerd Font"

[font.normal]
family = "FiraCode Nerd Font"

[[keyboard.bindings]]
chars = "\u0017"
key = "Back"
mods = "Control"
